# Generated by Django 5.2.11 on 2026-02-09 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_template', models.TextField()),
                ('eval_model', models.CharField(default='gpt-4o', max_length=100)),
                ('optimizer_model', models.CharField(default='gpt-4o', max_length=100)),
                ('target_score', models.FloatField(default=0.85)),
                ('max_iters', models.IntegerField(default=3)),
                ('original_avg_score', models.FloatField(default=0)),
                ('optimized_avg_score', models.FloatField(default=0)),
                ('improvement_pct', models.FloatField(default=0)),
                ('total_cost_usd', models.FloatField(default=0)),
                ('agent_filter', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(max_length=100, unique=True)),
                ('journey_name', models.CharField(blank=True, default='', max_length=300)),
                ('workflow_type', models.CharField(default='custom', max_length=100)),
                ('goal', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trace_id'], name='api_executi_trace_i_8cd9fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=200)),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('input_text', models.TextField(blank=True, default='')),
                ('output_text', models.TextField(blank=True, default='')),
                ('latency_ms', models.FloatField(default=0)),
                ('ttft_ms', models.FloatField(default=0)),
                ('tokens', models.IntegerField(default=0)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='api.executiontrace')),
            ],
            options={
                'ordering': ['trace', 'agent_name'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('input_text', models.TextField()),
                ('gold_text', models.TextField()),
                ('output_text', models.TextField()),
                ('score', models.FloatField()),
                ('iterations', models.IntegerField(default=0)),
                ('latency_ms', models.FloatField(default=0)),
                ('tokens', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.optimizationrun')),
            ],
            options={
                'ordering': ['run', 'row_index'],
            },
        ),
        migrations.CreateModel(
            name='RoutingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.TextField()),
                ('task_type', models.CharField(max_length=100)),
                ('latency_budget_ms', models.FloatField(blank=True, null=True)),
                ('cost_budget', models.FloatField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('model_id', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='router', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_type', '-created_at'], name='api_routing_task_ty_f8c8f8_idx')],
            },
        ),
    ]
