# Generated by Django 5.2.11 on 2026-02-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontrace',
            name='raw_journey',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
