# Generated by Django 5.2.11 on 2026-02-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_executiontrace_raw_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('total_traces', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('auto_evaluate', models.BooleanField(default=False)),
                ('user_goal', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_goal', models.TextField()),
                ('evaluation_mode', models.CharField(default='cascade', max_length=50)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('llm_calls_made', models.IntegerField(default=0)),
                ('duration_ms', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='api.executiontrace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
