# Generated by Django 5.2.11 on 2026-02-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_batchupload_evaluationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200)),
                ('original_prompt', models.TextField(blank=True, default='')),
                ('optimized_prompt', models.TextField()),
                ('cascade_feedback', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_overrides', to='api.executiontrace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trace', 'agent_name', 'is_active'], name='api_prompto_trace_i_b834e7_idx')],
            },
        ),
    ]
