# Generated by Django 5.2.11 on 2026-02-14 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_promptoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('user_goal', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('drifted', 'Drifted'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_actions', models.IntegerField(default=0)),
                ('drift_alerts', models.IntegerField(default=0)),
                ('checkpoint_interval', models.IntegerField(default=5)),
                ('llm_model', models.CharField(default='gpt-4o-mini', max_length=50)),
            ],
            options={
                'db_table': 'live_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriftAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_count', models.IntegerField()),
                ('aligned', models.BooleanField(default=False)),
                ('confidence', models.FloatField()),
                ('reason', models.TextField()),
                ('recommendation', models.TextField()),
                ('user_action', models.CharField(choices=[('paused', 'Paused Agent'), ('overridden', 'Override & Continue'), ('redirected', 'Changed Goal'), ('stopped', 'Stopped Agent'), ('pending', 'Pending User Decision')], default='pending', max_length=20)),
                ('recent_actions', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.livesession')),
            ],
            options={
                'db_table': 'drift_alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_num', models.IntegerField()),
                ('tool', models.CharField(max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('reasoning', models.TextField(blank=True)),
                ('input_text', models.TextField(blank=True)),
                ('output_text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.livesession')),
            ],
            options={
                'db_table': 'live_actions',
                'ordering': ['action_num'],
                'unique_together': {('session', 'action_num')},
            },
        ),
    ]
