# Generated by Django 5.2.11 on 2026-02-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_live_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentexecution',
            name='cached_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
